// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjQOTLFeHfE3M6gTM3YTAcsOMViA_AT94',
    appId: '1:521121341645:web:6637ac32cc690369060984',
    messagingSenderId: '521121341645',
    projectId: 'chatapp-25e33',
    authDomain: 'chatapp-25e33.firebaseapp.com',
    storageBucket: 'chatapp-25e33.appspot.com',
    measurementId: 'G-J2J85SSPKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBetQeuG6-iio_pLRx8Y4Qiz2xhJZytB_g',
    appId: '1:521121341645:android:752ac51badcff6e9060984',
    messagingSenderId: '521121341645',
    projectId: 'chatapp-25e33',
    storageBucket: 'chatapp-25e33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOgcPJsbjA4yCLBy4lD4_EAhJ-8ZG8zp8',
    appId: '1:521121341645:ios:f6a996ffe5c2c4bd060984',
    messagingSenderId: '521121341645',
    projectId: 'chatapp-25e33',
    storageBucket: 'chatapp-25e33.appspot.com',
    iosClientId: '521121341645-b72ei2uar69q5p7qs6k0lamo3jh5qor9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOgcPJsbjA4yCLBy4lD4_EAhJ-8ZG8zp8',
    appId: '1:521121341645:ios:bc7bd0145b79f12f060984',
    messagingSenderId: '521121341645',
    projectId: 'chatapp-25e33',
    storageBucket: 'chatapp-25e33.appspot.com',
    iosClientId: '521121341645-dgh7qgqnbmq4to6dn5u8admo0uvbepci.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
